language: java

jdk:
- oraclejdk8

services:
  - docker

install:
- true

addons:
  ssh_known_hosts: 140.143.154.41

script:
- gradle build -x test
- docker build -t qinlikang/erc20-svc .
- bash docker_push
- ssh root@140.143.154.41 "mkdir -p /opt/erc20-svc"
- scp ./restart.sh root@140.143.154.41:/opt/erc20-svc/
- ssh root@140.143.154.41 "docker pull qinlikang/erc20-svc; cd /opt/erc20-svc; bash restart.sh"

before_install:
- openssl aes-256-cbc -K $encrypted_c7216059caae_key -iv $encrypted_c7216059caae_iv
  -in id_travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

